### ISSUE TITLE
[Bug]: PopTracker Window cuts off information

### ISSUE THREAD

**Issue by SupremeNerd42** [ThePhar/APSM64TrackerPack#13]
### Tracker Pack Version

1.2.0

### PopTracker Version

v0.25.8

### Description of Issue

Also happens on SM64 Tracker version 1.2.1, and PopTracker v0.26.1 (I updated both while testing to make sure it wasn't either version being outdated)

The size of the Tracker window does not work on all screens, bottom information gets cut off and is unable to be accessed. I am using a laptop with Display Resolution of 1920x1080, and the Scale is set to 125%.
Setting PopTracker to Full Screen does not affect anything or give me access to these cut off things.

A temporary solution I found is changing the Scale of my screen, but it is not very accessible or easy for those with vision issues (like me), nor is it feasible for me to keep switching the Scale to be able to play and use the Tracker as it hurts my eyes.

Outside of this, the Tracker works very well and it is very visually clear.

### Additional Notes

Attached is a Fullscreen screenshot of the Tracker for visual reference of the issue.

![Screenshot 2024-06-30 123032](https://github.com/ThePhar/APSM64TrackerPack/assets/114674488/f7d80a59-7821-41fe-93fd-d0f3a8aa6f29)

**Comment by ThePhar** [comment]
Should be improved as of 1.3. Hopefully that works out for ya.
