### ISSUE TITLE
[Bug]: THI entrances for Tiny and Huge are backwards

### ISSUE THREAD

**Issue by Marioman6644** [ThePhar/APSM64TrackerPack#16]
### Tracker Pack Version

1.3.2

### PopTracker Version

0.29.0

### Description of Issue

Using the auto track entrances option (with AP) the tracker sets the entrances to the wrong versions of THI. Needs to be flipped.

ex. level entrance marked THI*H brings Mario into the version starting you near very tiny goombas (THI*T)

**Comment by ThePhar** [comment]
Good observation! I'll look into fixing this in next version. Thanks for the report!

**Comment by ThePhar** [comment]
Issue fixed in upcoming version 1.3.3, thanks.

**Comment by coolymike** [comment]
@ThePhar (mention because I do not have permission to reopen the issue) Just ran into this same issue on 1.3.3.

THI huge is indicated as being TotWC, THI small is indicated as THI. In-game, THI small is TotWC, THI huge is THI (small).
