### ISSUE TITLE
[Bug]: Shows TTC: 100 Coins Star possible with only ground pound

### ISSUE THREAD

**Issue by Karant-Maragan** [ThePhar/APSM64TrackerPack#18]
### Tracker Pack Version

1.3.2

### PopTracker Version

0.29.0

### Description of Issue

That shouldn't be possible.
![Tracker SM64](https://github.com/user-attachments/assets/0568b9dc-0eda-47ef-9824-f5ba5431e3bd)

**Comment by ThePhar** [comment]
That does feel incorrect to me. If nothing else, it definitely shouldn't be in logic if you can't even get the other stars in the stage.

I'll look into this to fix, thanks for the report!
