### ISSUE TITLE
[Bug]: "CCM: Wall Kicks will Work" does not get marked as accessible

### ISSUE THREAD

**Issue by RBmans** [ThePhar/APSM64TrackerPack#7]
### Tracker Pack Version

1.10

### PopTracker Version

0.26.0

### Description of Issue

CCM's Wall Kicks will Work shows as inaccessible no matter what moves/cannons/settings are selected. The ccm.lua looks like it has the correct logic so it seems it's just not being applied properly to the location.
![image](https://github.com/ThePhar/APSM64TrackerPack/assets/139954693/14bf0b60-eede-4b82-bb8a-e6afaf0b6698)

**Comment by ThePhar** [comment]
Not sure how I missed that one, let me see what's going on.

**Comment by ThePhar** [comment]
This has been fixed and released in v1.1.1, which will now auto-update too.
